name: PRABATH-MD Runner

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install PM2 & Dependencies
        run: |
          npm install -g pm2
          npm install

      - name: Start PRABATH-MD Bot
        run: |
          node start.js &
          echo "PRABATH-MD Bot එක සාර්ථකව GitHub Actions ඇතුළේ run වෙනවා..."
          sleep 21600
