name: PRABATH-MD GitHub Runner

on:
  push:
    branches: [ main ]
  workflow_dispatch: # මේකෙන් ඔයාට ඕනම වෙලාවක GitHub Actions එකට ගිහින් manually bot ව start කරන්න පුළුවන්.

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install PM2 & Dependencies
      run: |
        npm install -g pm2
        npm install

    - name: Start PRABATH-MD Bot
      env:
        SESSION_ID: "PRABATH-MD~EhFGIZJWNf4chz8" # ඔයාගේ Session ID එක මෙතනට දාන්න
        BOT_NUMBER: "94784604369" # ඔයාගේ Bot Number එක මෙතනට දාන්න
        DATABASE: "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" # ඔයාගේ DB Token එක මෙතනට දාන්න
      run: |
        node start.js &
        echo "PRABATH-MD Bot is running successfully inside GitHub Actions..."
        sleep 21600 # තත්පර 21600 කියන්නේ හරියටම පැය 6ක්. එතකන් Workflow එක alive තියාගන්නවා.
